name: tests

on:
  push:
    branches-ignore:
      - "gh-pages"
  pull_request:
    branches-ignore:
      - "gh-pages"

jobs:
  # Label of the container job
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
      - name: Tests
        run: go test
